# Generated by Django 2.1 on 2018-09-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180928_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='image',
        ),
    ]
